### ISSUE TITLE
NAACCR Data Dictionary with Allowable Values:Codes and Code Values

### ISSUE THREAD

**Issue by mgurley** [imsweb/naaccr-xml#118]
Does there exist anywhere the latest NAACCR Data Dictionary in XML format that contains Allowable Values/Codes and Code Values?  I see this here:

https://raw.githubusercontent.com/imsweb/naaccr-xml/master/src/main/resources/naaccr-dictionary-180.xml

But this just contains a dataType attribute for each 'ItemDef' element that only tells you to expect 'digits'.  Instead, I want to know that naaccrNum=1390 has a list of possible allowable values/codes:

Code  | Code Value
------------ | -------------
00 |	None, chemotherapy was not part of the planned first course of therapy.
01 | 	Chemotherapy, NOS.
02 |	Chemotherapy, single agent.
03 |	Chemotherapy, multiple agents.
82 |	Chemotherapy was not recommended/administered because it was contraindicated due to patient risk factors (i.e., comorbid conditions, advanced age).
85 |	Chemotherapy was not administered because the patient died prior to planned or recommended therapy.
86 |	Chemotherapy was not administered. It was recommended by the patient's physician, but was not administered as part of first-course therapy. No reason was stated in the patient record.
87 |	Chemotherapy was not administered; it was recommended by the patient's physician, but this treatment was refused by the patient, the patient's family member, or the patient's guardian. The refusal was noted in the patient record.
88 |	Chemotherapy was recommended, but it is unknown if it was administered.
99 |	It is unknown whether a chemotherapeutic agent(s) was recommended or administered because it is not stated in patient record; death certificate-only cases.

Kind of like how 'Data Standards and Data Dictionary – Query Builder' outputs a table of codes/code values.  See here: http://applications.naaccr.org/querybuilder/default.aspx?Version=18.  One that even goes as far as including all the SSDI possible code/code values, like is available here here:https://apps.naaccr.org/ssdi/list/, would be the absolute best.

**Comment by depryf** [comment]
Having the allowed values being part of the NAACCR XML standard and available via the dictionaries would be great, and it was considered when the standard was created a few years ago, but it is a big undertaking and it was decided it would be done at a later time. 

I think it makes a lot of sense and I hope the standard can be improved in the future with that functionality; I am just not sure when that might happen.

Note that the SSDI are an entire different beast and I don't think they will ever be part of a simple data exchange standard like NAACCR XML. They have their own framework (called staging) and our company also provides a Java library for that framework: https://github.com/imsweb/staging-client-java

**Comment by depryf** [comment]
The purpose of this library is to implement the NAACCR XML standard.

If the standard is updated to include allowed values and/or field documentation (for example), then the library will also be updated to include those. 

But this library won't move along with those heavy changes if they don't become part of the standard.

If anyone is interested in seeing those addition to the standard, I suggest starting a thread on the NAACCR XML forum: https://www.naaccr.org/forums/forum/naaccr-xml-standard/

**Comment by dckc** [comment]
FWIW, https://github.com/WerthPADOH/naaccr/tree/master/data-raw/code-labels seems like a pretty useful organization of the codes and values.

**Comment by depryf** [comment]
@dckc thanks for the info, I agree this seems like a very valuable piece of information and it's very well structured. Notifying @isaackcr since he is responsible for the NAACCR XML workgroup. Maybe one day the workgroup will use and/or contribute to that project!

**Comment by dckc** [comment]
In a [gpc-dev meeting this week][9Jul], Dr. Campbell suggested what I'm trying to do sounds like LOINC coding and @mgurley pointed out that some NAACCR/LOINC integration had been done a while back. I downloaded `Loinc_2.66.zip` and found that indeed, much of the detail is there.

I'm looking into how to extract the parts I need and I hope to do bit of a gap analysis.
https://github.com/kumc-bmi/naaccr-tumor-data/tree/loinc-csvdb

cc @ihafeez2k 

[9Jul]: http://listserv.kumc.edu/pipermail/gpc-dev/2019q3/005250.html

**Comment by dckc** [comment]
In a [recent comment][c], @rpinder-zz  writes:
> indeed, many of us have scraped the HECK out of that one !! lots of folks are moving towards your ask here... and even taking it one step further than the current Chap VII to include the field VALUES incorporated into electronic (xml) format. progress....

Care to elaborate, @rpinder-zz ? "lots of folks"? Such as? How would I reach them?

[c]: https://github.com/imsweb/naaccr-xml/issues/156#issuecomment-524403340

**Comment by depryf** [comment]
I think what @rpinder-zz meant is that many people (including myself) have scrapped the online NAACCR dictionary information (http://datadictionary.naaccr.org/?c=10) because there was no other way to get the full NAACCR field documentation in a computer-friendly way.

For example, here is a library I also maintain that provides the field documentation the same way it's presented online:
https://github.com/imsweb/layout/tree/master/src/main/resources/layout/fixed/naaccr/doc/naaccr18
Having that documentation part of a library like that allows me to use it in standalone software that don't require online connection.

Note that what NAACCR calls dictionary is not the same as the NAACCR XML dictionaries used in this library.  The purpose of the online NAACCR dictionary is to provide field documentation for all the NAACCR data items. The purpose of the NAACCR XML dictionaries is to allow a program to read and understand a NAACCR XML data files.

There is certainly some overlapping between the two, and it's unfortunate that both concepts have the same name. But they are different, and they are not maintained by the same group of people...

**Comment by mgurley** [comment]
Sounds like to me we should converge all these efforts of scrapping of the NAACCR dictionary information (http://datadictionary.naaccr.org/?c=10) and serialization of multiple calls to the SEER API (https://api.seer.cancer.gov/) efforts together into a **new** library to get full NAACCR field documentation in a computer-friendly way.

**Comment by depryf** [comment]
For folks interested in the full documentation, SEER API does have an end-point that returns the documentation for a given NAACCR data item. But it's a block of HTML (as it appears on http://datadictionary.naaccr.org/?c=10), it's not some well structure data. 

It's actually the same information contained in this library: https://github.com/imsweb/layout/tree/master/src/main/resources/layout/fixed/naaccr/doc/naaccr18

As @dckc mentioned earlier in this thread, someone took the time to create pick lists for all the allowed values for many data items: https://github.com/WerthPADOH/naaccr/tree/master/data-raw/code-labels

I agree a new project combining those effort and providing combined documentation (full HTML, pick lists, other?) in a centralized place sounds like a great idea.  Mainly because the focus of this NAACCR XML library is to read/write NAACCR XML data, and providing field documentation (while very useful) is not needed for those operations.
