### ISSUE TITLE
Adding new NaaccrXmlDictionaryUtils validation functions

### ISSUE THREAD

**Issue by howew** [imsweb/naaccr-xml#125]
Any chance you can add validation methods that return a collection of strings rather than stopping after the first error it finds?

I’m thinking of cases where someone has multiple issues in a file.  It would be nice to know all of the issues up front rather than one at a time.  They could presumably get an error, fix it, get another error, fix it, and so on.

**Comment by depryf** [comment]
This work has been completed.

I realize this might break some code but the fix is trivial (to check if valid, check for empty list instead of null, and to get the first error like before, just get the first element of the list).

So hopefully this won't be a big deal for anyone (and the dictionary validation is mostly internal to this library).
