### ISSUE TITLE
99999999 in date field

### ISSUE THREAD

**Issue by dckc** [imsweb/naaccr-xml#151]
When I try to convert the tumor registry file from KU Med Center to XML with validation on, I get lots of these errors:

```
Line 1, item 'dateCaseReportReceived' (#2111): invalid value according to data type 'date' [99999999]
Line 2, item 'dateCaseReportReceived' (#2111): invalid value according to data type 'date' [99999999]
Line 3, item 'dateCaseReportReceived' (#2111): invalid value according to data type 'date' [99999999]
```

Is 99999999 actually invalid? Or is it a sentinel for "unknown"?

**Comment by depryf** [comment]
The value 99999999 is indeed invalid for a NAACCR date.

Several years ago (I think it was for NAACCR 12), NAACCR introduced the "flavors of null" for the dates: instead of using special values for unknown dates (like 9's or 0's) they attached a date flag to each date data item. And so 99999999 is not supposed to appear in the data anymore; instead the date is supposed to be left blank and the flag is supposed to have a value.

Note that each flag has it's own list of allowed values and so computing a flag from an unknown date can be different from one date to another.

Also note that those are just warnings; the resulting XML file is still valid XML and you can still use it in other software.

**Comment by dckc** [comment]
Interesting. https://www.kumc.edu/kcr/ bears a 2015 NAACCR gold certification, so I thought the data was mostly good. I don't look forward to special cases for non-standard data, but I guess that's what I have to do.
