### ISSUE TITLE
Add items 351,352,353,354 to the layout

### ISSUE THREAD

**Issue by howew** [imsweb/naaccr-xml#152]
These are new data items (GeoLocation).  Can they be added to the library?

**Comment by depryf** [comment]
@howew the dictionary already contains those items, but they are grouped items and so you get them by calling the "getGroupedItems" method instead of the "getItems" one.

They were separated that way because grouped items can't appear in XML data files (that would be two ways to provide the same data in the file). And so the library will never return grouped items when reading a data file (if you really want the values for grouped items, you will have to build them yourself by concatenating the regular items.

Grouped items were added to the specs because some specific software still use them but it's an old concept that doesn't really fit with the new XML specs.
