### ISSUE TITLE
add naaccr-xml-utility.jar to release artifacts?

### ISSUE THREAD

**Issue by dckc** [imsweb/naaccr-xml#155]
It would be nice to be able to grab naaccr-xml-utility.jar from maven or github releases.

**Comment by depryf** [comment]
The utility tool is available as a release artifact (available on the Releases page of this project): 

![image](https://user-images.githubusercontent.com/2622206/62385672-bb28b200-b523-11e9-93c0-4bd1bd4d9855.png)

It's not a JAR file because the tool comes with some JAR dependencies and its own embedded Java Runtime Environment, and so it's packed as a ZIP file instead.

**Comment by dckc** [comment]
silly me. thanks!
