### ISSUE TITLE
RFE: add item section to data dictionary

### ISSUE THREAD

**Issue by dckc** [imsweb/naaccr-xml#156]
In presenting the NAACCR data dictionary as an i2b2 ontology, I make use of the section from [Chapter VII: Record Layout Table][ch7] to divide the items into manageable lists.

To date, I have scraped this from PDF or HTML documents, but it would be more straightforward and convenient to get it as part of the data dictionaries here -- in particular, it would make the license more clear.

[ch7]: http://datadictionary.naaccr.org/default.aspx?c=7

**Comment by rpinder-zz** [comment]
indeed, many of us have scraped the HECK out of that one !!
lots of folks are moving towards your ask here...  and even taking it one step further than the current Chap VII to include the field VALUES incorporated into electronic (xml) format.
progress....
r

On 8/23/19 10:34 AM, Dan Connolly wrote:

In presenting the NAACCR data dictionary as an i2b2 ontology, I make use of the section from Chapter VII: Record Layout Table<https://urldefense.proofpoint.com/v2/url?u=http-3A__datadictionary.naaccr.org_default.aspx-3Fc-3D7&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=rmPFyafC9OwcDTfmvJ3NVg&m=ncBIWT8HW3A_H-nzBgFs5zoL-34Dtb8MIIY6KSnjheM&s=rL3z63B0qt3B3hAvh4LEwyRuTjxlcZv3rIZOHPZV5HI&e=> to divide the items into manageable lists.

To date, I have scraped this from PDF or HTML documents, but it would be more straightforward and convenient to get it as part of the data dictionaries here -- in particular, it would make the license more clear.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_imsweb_naaccr-2Dxml_issues_156-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DACSAZEL66T4VICNPFDLAKBDQGANSTA5CNFSM4IPB2BW2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HHC7LVA&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=rmPFyafC9OwcDTfmvJ3NVg&m=ncBIWT8HW3A_H-nzBgFs5zoL-34Dtb8MIIY6KSnjheM&s=7YI4EqUWVULR4nQvfOlpDJV2_wkIJnn1c1LT1FQo8BQ&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACSAZEPF6HQLCUTGR2MWXPDQGANSTANCNFSM4IPB2BWQ&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=rmPFyafC9OwcDTfmvJ3NVg&m=ncBIWT8HW3A_H-nzBgFs5zoL-34Dtb8MIIY6KSnjheM&s=sf99dFE0b26vJxz0ytNx-GPdaqmalWrPH51VDSJ7lJ4&e=>.


...
r

**Comment by dckc** [comment]
I see a handy spreadsheet
https://www.naaccr.org/wp-content/uploads/2019/08/Chapter-VII-Excel-worsheet-9-Aug-2019.xlsx

I'm still struggling to find license / terms and conditions...
links to http://applications.naaccr.org/terms-of-use/ doesn't seem to work.
I wrote to info@naaccr.org

**Comment by depryf** [comment]
I believe the NAACCR XML work group already discussed the sections. It was decided (I am only reporting the decision, it wasn't "my" decision by any mean) that the primary goal of the NAACCR XML dictionary was to allow a program to read the XML data, and that sections were not needed to accomplish that. Sections are like the fields documentation, they are useful to end-users/programs, but not to the program reading the data.

It's not impossible that the sections will be added to the NAACCR XML Specifications one day, but as far as I know, it's not really on the road map.

On a site, I maintain those sections in an XML file in another project; it's a file that describes the NAACCR fixed-column format: 
https://github.com/imsweb/layout/blob/master/src/main/resources/layout/fixed/naaccr/naaccr-18-layout.xml
If that works for you, you are welcome to get them from that project!

**Comment by dckc** [comment]
Yes, that will do nicely. Thanks!

**Comment by rpinder-zz** [comment]
Thanks.  Definitely on my radar.

Just got home from bike ride btw.  The usual 50 miles.  I hate cars.  :-)

--Rich

Richard Moldwin, M.D., Ph.D.
Lead Physician Informaticist
College of American Pathologists
325 Waukegan Rd.
Northfield, IL 60093
rmoldwin@cap.org<mailto:rmoldwin@cap.org>
Alt: 847-983-0085
Cell: 224-343-3462
(Sent from iPhone)

On Aug 23, 2019, at 12:46 PM, Rich Pinder <rpinder@usc.edu<mailto:rpinder@usc.edu>> wrote:

indeed, many of us have scraped the HECK out of that one !!
lots of folks are moving towards your ask here...  and even taking it one step further than the current Chap VII to include the field VALUES incorporated into electronic (xml) format.
progress....
r

On 8/23/19 10:34 AM, Dan Connolly wrote:

In presenting the NAACCR data dictionary as an i2b2 ontology, I make use of the section from Chapter VII: Record Layout Table<https://urldefense.proofpoint.com/v2/url?u=http-3A__datadictionary.naaccr.org_default.aspx-3Fc-3D7&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=rmPFyafC9OwcDTfmvJ3NVg&m=ncBIWT8HW3A_H-nzBgFs5zoL-34Dtb8MIIY6KSnjheM&s=rL3z63B0qt3B3hAvh4LEwyRuTjxlcZv3rIZOHPZV5HI&e=> to divide the items into manageable lists.

To date, I have scraped this from PDF or HTML documents, but it would be more straightforward and convenient to get it as part of the data dictionaries here -- in particular, it would make the license more clear.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_imsweb_naaccr-2Dxml_issues_156-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DACSAZEL66T4VICNPFDLAKBDQGANSTA5CNFSM4IPB2BW2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HHC7LVA&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=rmPFyafC9OwcDTfmvJ3NVg&m=ncBIWT8HW3A_H-nzBgFs5zoL-34Dtb8MIIY6KSnjheM&s=7YI4EqUWVULR4nQvfOlpDJV2_wkIJnn1c1LT1FQo8BQ&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACSAZEPF6HQLCUTGR2MWXPDQGANSTANCNFSM4IPB2BWQ&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=rmPFyafC9OwcDTfmvJ3NVg&m=ncBIWT8HW3A_H-nzBgFs5zoL-34Dtb8MIIY6KSnjheM&s=sf99dFE0b26vJxz0ytNx-GPdaqmalWrPH51VDSJ7lJ4&e=>.


...
r
