### ISSUE TITLE
stable xml ids? data dictionary tracking?

### ISSUE THREAD

**Issue by dckc** [imsweb/naaccr-xml#157]
On the NAACCR ListServ I just saw that the xml IDs for a couple items were "corrected".

What does that mean for NAACCR XML data that used `phase1RadiationPrimaryTxVolume` for item 3884 without recording the item number? It would be pretty difficult to recover such data.

This library seems to treat the xmlId as required and the item number as optional. Is that wise? The numbers look a lot more stable, to me.

Hmm... it looks like the bug didn't affect this library... how is that?
https://github.com/imsweb/naaccr-xml/blob/master/src/main/resources/naaccr-dictionary-180.xml#L3617

Doesn't this library track https://www.naaccr.org/data-standards-data-dictionary/ ?

**Comment by depryf** [comment]
The dictionary XML file contained in this library is meant to be used by programs. It is the "official" repository of NAACCR XML IDs (as far as I know). 

The XML IDs mentioned in that notification are maintained by "by hand" by NAACCR staff on their website. It is meant to be a reference for humans, not programs.

The IDs should be in sync in both places, but it seems there were a couple of cut/paste mistakes on the NAACCR website. As you mentioned, this won't affect any software since the XML dictionary in this library already had the correct values.

When the NAACCR XML specifications were designed, one requirements was that a human should be able to understand the content when opening a data file. That's why the IDs are required. The numbers are nice, but they are technically not needed by a program to understand the data. And so the numbers are optional in the data files (but they are still required in the dictionaries). 

Renaming XML IDs is exceptional but it has happened.

A bunch of items introduced in version 18 got renamed a few months after they went live because the specifications changed to a maximum of 32 characters for IDs (to make SAS happy). 

It is also possible that IDs changed from one version to another because an organization completely changes the meaning of a data item (one would argue they should then use a different number but sometimes it's still related and they want to keep the same numbers). In that case it makes more sense to change the ID instead of keeping one that looks nothing like the data item name.

Anyway, it's not a good thing to change IDs and we try really hard not to do it, but like I said, there are exceptional situations.  I try to document those in the [wiki pages](https://github.com/imsweb/naaccr-xml/wiki/3:-NAACCR-XML-Dictionaries).

**Comment by depryf** [comment]
There is no work that needs to be done for this issue, I am going to close it.
