### ISSUE TITLE
Custom User Dictionary Should Allow ItemDef elements from Default User Dictionary

### ISSUE THREAD

**Issue by isaackcr** [imsweb/naaccr-xml#43]
If you create a custom user dictionary with some of your own ItemDefs like this:

```XML
        <ItemDef naaccrId="packYears"
            naaccrNum="9600"
            naaccrName="Custom State/Requestor Items"
            startColumn="2340"
            length="3"
            recordTypes="A,M,C,I"
            parentXmlElement="Tumor"
            trim="none"/>
```
you cannot include any ItemDefs from the default User Dictionary like this:

```XML
 <ItemDef naaccrId="npcrSpecificField"
            naaccrNum="3720"
            naaccrName="NPCR Specific Field"
            startColumn="1306"
            length="75"
            recordTypes="A,M,C,I"
            parentXmlElement="Tumor"
            trim="none"/>
```

The problem is line 328 of NaaccrXmlDictionaryUtils.validateDictionary, it will throw an error if any of the custom ItemDef naaccrIds matches a naaccrId in the default user dictionary. Instead, it should check to see if the custom user dictionary is re-defining an existing ItemDef and throw the error  - you should be able to include a valid, unchanged ItemDef from the default user dictionary.

**Comment by depryf** [comment]
Agreed. I will work on a fix as soon as I can.

**Comment by depryf** [comment]
This is fixed.

I thought it was overkill to enforce all the attributes to be the same if you re-define an item from the default user dictionary since some of those attribute really don't matter too much. So if one redefines the same item (like the "npcrSpecificField" from the example), the following attributes need to be the same:
- naaccrNum
- naaccrName
- startColumn
- length
- recordTypes
- parentXmlElement
-dataType

This fix will be available in the next release.
